name: openmob_hub
description: "OpenMob Hub - Self-hosted mobile device automation"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  rxdart: ^0.28.0
  rxdart_flutter: ^0.0.2
  xml: ^6.0.0
  window_manager: ^0.5.1
  http: ^1.4.0

flutter:
  uses-material-design: true
